#ifndef TETRIS_CONFIG_H
#define TETRIS_CONFIG_H

// gameplay keybinds
#define TETRIS_KEYBIND_ROTATE_CW  KEY_X
#define TETRIS_KEYBIND_ROTATE_CCW KEY_Z
#define TETRIS_KEYBIND_HOLD_PIECE KEY_C
#define TETRIS_KEYBIND_MOVE_LEFT  KEY_LEFT
#define TETRIS_KEYBIND_MOVE_RIGHT KEY_RIGHT
#define TETRIS_KEYBIND_HARD_DROP  KEY_SPACE
#define TETRIS_KEYBIND_SOFT_DROP  KEY_DOWN

// system keybinds
#define TETRIS_KEYBIND_RESTART      KEY_PERIOD
#define TETRIS_KEYBIND_TOGGLE_DEBUG KEY_COMMA

#endif
